[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Root serves index.html automatically, no redirect needed

# Serve beauty page at /beauty path
[[redirects]]
  from = "/beauty"
  to = "/beauty/index.html"
  status = 200

[[redirects]]
  from = "/beauty/*"
  to = "/beauty/:splat"
  status = 200

# Serve saas content at /saas path
[[redirects]]
  from = "/saas"
  to = "/saas/index.html"
  status = 200

[[redirects]]
  from = "/saas/*"
  to = "/saas/:splat"
  status = 200

# Serve ecom-checklist at /ecom-checklist path
[[redirects]]
  from = "/ecom-checklist"
  to = "/ecom-checklist/index.html"
  status = 200

[[redirects]]
  from = "/ecom-checklist/*"
  to = "/ecom-checklist/:splat"
  status = 200

# Serve fashion page at /fashion path
[[redirects]]
  from = "/fashion"
  to = "/fashion/index.html"
  status = 200

[[redirects]]
  from = "/fashion/*"
  to = "/fashion/:splat"
  status = 200

# Serve ecommerce page at /ecommerce path
[[redirects]]
  from = "/ecommerce"
  to = "/ecommerce/index.html"
  status = 200

[[redirects]]
  from = "/ecommerce/*"
  to = "/ecommerce/:splat"
  status = 200

# Block digital-products from production (only accessible in dev/preview)
[[redirects]]
  from = "/digital-products"
  to = "/404.html"
  status = 404
  force = true
  condition = "Country=!dev"

[[redirects]]
  from = "/digital-products/*"
  to = "/404.html"
  status = 404
  force = true
  condition = "Country=!dev"

# Thank you page redirects
[[redirects]]
  from = "/thank-you"
  to = "/thank-you.html"
  status = 200

[[redirects]]
  from = "/saas/thank-you"
  to = "/saas/thank-you.html"
  status = 200

[[redirects]]
  from = "/ecom-checklist/thank-you"
  to = "/ecom-checklist/thank-you.html"
  status = 200

[[redirects]]
  from = "/fashion/thank-you"
  to = "/fashion/thank-you.html"
  status = 200

[[redirects]]
  from = "/ecommerce/thank-you"
  to = "/ecommerce/thank-you.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com https://connect.facebook.net https://snap.licdn.com https://www.google.com https://cdnjs.cloudflare.com https://unpkg.com https://cdn.jsdelivr.net https://eu.i.posthog.com https://eu-assets.i.posthog.com; img-src 'self' data: https://www.google-analytics.com https://www.googletagmanager.com https://www.facebook.com https://px.ads.linkedin.com https://www.google.com; font-src 'self' https: data: https://fonts.gstatic.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://unpkg.com https://cdn.jsdelivr.net; connect-src 'self' https://www.google-analytics.com https://www.googletagmanager.com https://stats.g.doubleclick.net https://www.facebook.com https://connect.facebook.net https://px.ads.linkedin.com https://www.google.com https://www.google.com/ccm/collect https://eu.i.posthog.com; frame-src 'self' https://www.youtube.com https://www.facebook.com https://consent.google.com;"

# Stricter CSP for fashion page (less dependencies)
[[headers]]
  for = "/fashion/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://cdnjs.cloudflare.com https://unpkg.com https://cdn.jsdelivr.net https://eu.i.posthog.com; img-src 'self' data: https:; font-src 'self' https: data: https://fonts.gstatic.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; connect-src 'self' https://eu.i.posthog.com; frame-src 'self';"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"


[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"