[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Root serves index.html automatically, no redirect needed

# Serve beauty page at /beauty path
[[redirects]]
  from = "/beauty"
  to = "/beauty/index.html"
  status = 200

[[redirects]]
  from = "/beauty/*"
  to = "/beauty/:splat"
  status = 200

# Serve saas content at /saas path
[[redirects]]
  from = "/saas"
  to = "/saas/index.html"
  status = 200

[[redirects]]
  from = "/saas/*"
  to = "/saas/:splat"
  status = 200

# Serve ecom-checklist at /ecom-checklist path
[[redirects]]
  from = "/ecom-checklist"
  to = "/ecom-checklist/index.html"
  status = 200

[[redirects]]
  from = "/ecom-checklist/*"
  to = "/ecom-checklist/:splat"
  status = 200

# Serve fashion page at /fashion path
[[redirects]]
  from = "/fashion"
  to = "/fashion/index.html"
  status = 200

[[redirects]]
  from = "/fashion/*"
  to = "/fashion/:splat"
  status = 200

# Block digital-products from production (only accessible in dev/preview)
[[redirects]]
  from = "/digital-products"
  to = "/404.html"
  status = 404
  force = true
  condition = "Country=!dev"

[[redirects]]
  from = "/digital-products/*"
  to = "/404.html"
  status = 404
  force = true
  condition = "Country=!dev"

# Thank you page redirects
[[redirects]]
  from = "/thank-you"
  to = "/thank-you.html"
  status = 200

[[redirects]]
  from = "/saas/thank-you"
  to = "/saas/thank-you.html"
  status = 200

[[redirects]]
  from = "/ecom-checklist/thank-you"
  to = "/ecom-checklist/thank-you.html"
  status = 200

[[redirects]]
  from = "/fashion/thank-you"
  to = "/fashion/thank-you.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' https:; img-src 'self' https: data:; font-src 'self' https: data:; connect-src 'self' https://api.posthog.com https://*.supabase.co https://*.facebook.com;"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"


[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"